pipeline:
  build:
    image: ruby:2.3
    commands:
      - bundle install
      - ruby test.rb
  publish:
    image: plugins/docker
    username: ${DRONE_USERNAME}
    password: ${DRONE_PASSWORD}
    email: ${DRONE_EMAIL}
    repo: dockerlapaz/votacion-ruby
    tags: ${DRONE_BUILD_NUMBER}
services:
  redis:
    image: redis:alpine
