pipeline:
  build:
    image: ruby:2.3
    commands:
      - bundle install
      - ruby test.rb
  publish:
    image: plugins/docker
    debug: true
    username: yamilurbina
    password: ${DRONE_PASSWORD}
    email: hello@yamilurbina.com
    repo: dockerlapaz/votacion2
    tags: ${DRONE_BUILD_NUMBER}
services:
  redis:
    image: redis:alpine
